import { CabinetMember } from './types.ts';

export const ALL_CABINET_MEMBERS: CabinetMember[] = [
  // =================== BADAN PENGURUS HARIAN (BPH) ===================
  {
    id: 'ph-1',
    name: 'Raditya Arya Pratama',
    role: 'Ketua Umum OSIS',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XII MIPA 1',
    nis: '2223.10.041',
    email: 'raditya.arya@osis.sman1adhirajasa.sch.id',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0ft2uiBFLCKTUxz61MKHwCGhpXMxMeKgp2uPS8Tqo2LZQ0kvGHg6HVefoP03f-cYyzlfpMR2Of-eM53Nj1LSDD8QWDhp-qTSE0_0MpGK2dpxw9WocKGEH81Bc9rfJjlI7w3YjHFgXL3q6WnaSN-py5xneapYrtv4cg1jqp9elv5QNk5lg07gG69pXB-qcPMwwfSRGq14Ob-YLv7qrz8nDSDASxAc0vURt_m_y_R1kL0UPazU9ONY',
    isBph: true,
    isCoordinator: true,
    bio: 'Memimpin kepengurusan Kabinet Cakrawala Bhakti 2024/2025. Peraih Medali Emas Debat Konstitusi Siswa Nasional.',
    instagram: '@raditya.pratama'
  },
  {
    id: 'ph-2',
    name: 'Anindya Putri Larasati',
    role: 'Wakil Ketua Umum I',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XI MIPA 3',
    nis: '2324.11.088',
    email: 'anindya.larasati@osis.sman1adhirajasa.sch.id',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBknAFQ1YaouN4-l1E5RWCj7oZgANlsa5cwTPRMTK4GsLmX6JtID6j1jOjm3h52CNPWv6bZJo_jjFzPg2yVhJP5xOqyYNDe6K9GSXekIA1NUs98MmkTpsNxsZeYIfUi0iMVy0BX0dDCN5VvGKmkamgxgeuZtTqaVb3jxzkbcZVavsLsdUE7bu4ghv1LG_72lT2hniyaAJGEV8XngFgYu47GjLfJwSM010srGhMLo6SXrJhKhIYR9Ns',
    isBph: true,
    isCoordinator: true,
    bio: 'Mengoordinasikan kerja internal 10 Seksi Bidang dan tata kelola program tahunan OSIS.',
    instagram: '@anindya.larasati'
  },
  {
    id: 'ph-3',
    name: 'M. Rizky Pratama',
    role: 'Wakil Ketua Umum II',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XI IPS 2',
    nis: '2324.11.095',
    email: 'rizky.pratama@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    isBph: true,
    isCoordinator: false,
    bio: 'Penanggung jawab hubungan eksternal, advokasi kemitraan lintas sekolah, dan koordinasi MPK.',
    instagram: '@rizky.pratama'
  },
  {
    id: 'ph-4',
    name: 'M. Fadhil Ramadhan',
    role: 'Sekretaris Umum',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XII IPS 2',
    nis: '2223.10.192',
    email: 'fadhil.ramadhan@osis.sman1adhirajasa.sch.id',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8Z_p4AT_UTWjLHTegdFFzRl51OEwhINIewkFsYNDaCo1CrP3c3w6PIjR451Ku-p_bNjrBQzwUbyj9K6n-GWKJzoWMtZ3zPe9B7kTsqoSuHsOWbovXonSe3umi23dIrw93_NEIkVh9fZ43B9jzfL_fC9mhxgmtf723I7yO_2sK280P16QmX4XmFcfIBnNJUC5LZronfH20KIzOeiLSz5pfy8Kn4ofLTI26quSLEQDOF6bF1nks5Hg',
    isBph: true,
    isCoordinator: false,
    bio: 'Penanggung jawab administrasi kearsipan, legalitas SK kepengurusan, dan inventarisasi dokumen organisasi.',
    instagram: '@fadhil.rmdhn'
  },
  {
    id: 'ph-5',
    name: 'Aurelia Khansa',
    role: 'Wakil Sekretaris',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XI MIPA 2',
    nis: '2324.11.104',
    email: 'aurelia.khansa@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isBph: true,
    isCoordinator: false,
    bio: 'Pengelolaan notulensi musyawarah kerja, surat menyurat digital, dan arsip presensi sidang pleno.',
    instagram: '@aureliakhansa'
  },
  {
    id: 'ph-6',
    name: 'Zahra Almira',
    role: 'Bendahara Umum',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XI MIPA 2',
    nis: '2324.11.144',
    email: 'zahra.almira@osis.sman1adhirajasa.sch.id',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDva3DNShvEl3wETV9mW3_f9QVRAex33EgwzeElvxBhI1Xa7GU8bMFfGl9ygbtCwBg9G_aKKo40RkRMskSSRs1u74DD9Jb_b28ZF8S8fpBgoeb2O985_Jqe3-wPVgSVnyz98l8mmsRsUnpElFVhJ6dTHiRv_IbF95O5alSFvk_ARUylduCS-jwTDBqqsGTXEiN0nI2UGo9ag6r0LFQL-SWniQgMRGW4PLUNi2JH1Y50xB-tT0eTOWU',
    isBph: true,
    isCoordinator: false,
    bio: 'Mengelola tata kelola keuangan organisasi secara transparan melalui buku kas mingguan terbuka.',
    instagram: '@zahra.almira'
  },
  {
    id: 'ph-7',
    name: 'Daffa Ibnu Sina',
    role: 'Wakil Bendahara',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XI IPS 1',
    nis: '2324.11.150',
    email: 'daffa.ibnu@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    isBph: true,
    isCoordinator: false,
    bio: 'Pencatatan realisasi dana proposal kegiatan dan audit bukti pembayaran belanja kepanitiaan.',
    instagram: '@daffa.ibnu'
  },
    {
    id: 'ph-7',
    name: 'Daffa Ibnu Sina',
    role: 'Wakil Bendahara',
    division: 'BPH',
    divisionName: 'Badan Pengurus Harian',
    classGrade: 'XI IPS 1',
    nis: '2324.11.150',
    email: 'daffa.ibnu@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    isBph: true,
    isCoordinator: false,
    bio: 'Pencatatan realisasi dana proposal kegiatan dan audit bukti pembayaran belanja kepanitiaan.',
    instagram: '@daffa.ibnu'
  },

  // =================== SEKBID I: KETAQWAAN TERHADAP TUHAN YME ===================
  {
    id: 'sekbid-1-1',
    name: 'Ahmad Zaki',
    role: 'Koordinator Sekbid I',
    division: 'Sekbid I',
    divisionName: 'Ketaqwaan Terhadap Tuhan YME',
    classGrade: 'XII MIPA 4',
    nis: '2223.10.012',
    email: 'ahmad.zaki@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Membimbing pembinaan kerohanian Islam & Kristen serta toleransi antarumat beragama di sekolah.'
  },
  {
    id: 'sekbid-1-2',
    name: 'Farhan Maulana',
    role: 'Staf Kerohanian Islam (Rohis)',
    division: 'Sekbid I',
    divisionName: 'Ketaqwaan Terhadap Tuhan YME',
    classGrade: 'XI MIPA 1',
    nis: '2324.11.020',
    email: 'farhan.maulana@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    bio: 'Pengorganisasian kajian Jumat berkah dan peringatan Maulid Nabi serta Isra Mi’raj.'
  },
  {
    id: 'sekbid-1-3',
    name: 'Nabilah Zahra',
    role: 'Staf Keputrian Rohis',
    division: 'Sekbid I',
    divisionName: 'Ketaqwaan Terhadap Tuhan YME',
    classGrade: 'X-2',
    nis: '2425.10.035',
    email: 'nabilah.zahra@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    bio: 'Pengelolaan kegiatan keputrian Jumat dan kegiatan bakti sosial Ramadhan berkah.'
  },
  {
    id: 'sekbid-1-4',
    name: 'Samuel Christian',
    role: 'Staf Kerohanian Kristen & Katolik (Rokris)',
    division: 'Sekbid I',
    divisionName: 'Ketaqwaan Terhadap Tuhan YME',
    classGrade: 'XI IPS 3',
    nis: '2324.11.042',
    email: 'samuel.christian@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    bio: 'Koordinator kebaktian padang siswa Kristiani dan perayaan Natal sekolah.'
  },

  // =================== SEKBID II: WAWASAN KEBANGSAAN & NASIONALISME ===================
  {
    id: 'sekbid-2-1',
    name: 'Bagas Pratista',
    role: 'Koordinator Sekbid II',
    division: 'Sekbid II',
    divisionName: 'Wawasan Kebangsaan & Nasionalisme',
    classGrade: 'XI IPS 1',
    nis: '2324.11.055',
    email: 'bagas.pratista@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Penyelenggara upacara bendera reguler dan peringatan hari besar kebangsaan.'
  },
  {
    id: 'sekbid-2-2',
    name: 'Arya Wardhana',
    role: 'Staf Pasukan Upacara & Paskibra',
    division: 'Sekbid II',
    divisionName: 'Wawasan Kebangsaan & Nasionalisme',
    classGrade: 'XII MIPA 3',
    nis: '2223.10.060',
    email: 'arya.wardhana@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    bio: 'Pelatih kedisiplinan formasi paskibraka unit SMAN 1 Adhirajasa.'
  },
  {
    id: 'sekbid-2-3',
    name: 'Siti Nurhaliza',
    role: 'Staf Protokoler & Upacara',
    division: 'Sekbid II',
    divisionName: 'Wawasan Kebangsaan & Nasionalisme',
    classGrade: 'X-4',
    nis: '2425.10.071',
    email: 'siti.nurhaliza@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    bio: 'Pengatur susunan acara protokoler upacara hari kemerdekaan dan apel disiplin.'
  },
  {
    id: 'sekbid-2-4',
    name: 'Dika Adriansyah',
    role: 'Staf Wawasan Konstitusi',
    division: 'Sekbid II',
    divisionName: 'Wawasan Kebangsaan & Nasionalisme',
    classGrade: 'XI MIPA 5',
    nis: '2324.11.078',
    email: 'dika.adriansyah@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    bio: 'Penyelenggara seminar wawasan kebangsaan pemuda dan parade pahlawan nasional.'
  },

  // =================== SEKBID III: PENDIDIKAN KARAKTER & BELA NEGARA ===================
  {
    id: 'sekbid-3-1',
    name: 'Dimas Nugraha',
    role: 'Koordinator Sekbid III',
    division: 'Sekbid III',
    divisionName: 'Pendidikan Karakter & Bela Negara',
    classGrade: 'XII MIPA 2',
    nis: '2223.10.089',
    email: 'dimas.nugraha@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Penanggung jawab pembinaan kedisiplinan tata tertib siswa dan kepengurusan LDKS.'
  },
  {
    id: 'sekbid-3-2',
    name: 'Rayhan Putra',
    role: 'Staf Ketertiban Siswa',
    division: 'Sekbid III',
    divisionName: 'Pendidikan Karakter & Bela Negara',
    classGrade: 'XI IPS 2',
    nis: '2324.11.092',
    email: 'rayhan.putra@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?auto=format&fit=crop&w=600&q=80',
    bio: 'Operasi penertiban seragam dan atribut kepatuhan siswa setiap pagi.'
  },
  {
    id: 'sekbid-3-3',
    name: 'Kayla Safira',
    role: 'Staf Budaya Disiplin',
    division: 'Sekbid III',
    divisionName: 'Pendidikan Karakter & Bela Negara',
    classGrade: 'X-1',
    nis: '2425.10.098',
    email: 'kayla.safira@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    bio: 'Edukasi gerakan anti-bullying dan pembiasaan budaya 5S (Senyum, Sapa, Salam, Sopan, Santun).'
  },
  {
    id: 'sekbid-3-4',
    name: 'Tegar Wicaksono',
    role: 'Staf Pengamanan Kegiatan',
    division: 'Sekbid III',
    divisionName: 'Pendidikan Karakter & Bela Negara',
    classGrade: 'XI MIPA 4',
    nis: '2324.11.101',
    email: 'tegar.wicaksono@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=600&q=80',
    bio: 'Koordinasi keamanan dan mitigasi evakuasi kebencanaan saat event akbar sekolah.'
  },

  // =================== SEKBID IV: KEPRIBADIAN UNGGUL & KEWIRAUSAHAAN ===================
  {
    id: 'sekbid-4-1',
    name: 'Naufal Rizky',
    role: 'Koordinator Sekbid IV',
    division: 'Sekbid IV',
    divisionName: 'Kepribadian Unggul & Wawasan Kewirausahaan',
    classGrade: 'XI IPS 3',
    nis: '2324.11.115',
    email: 'naufal.rizky@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Pengembangan unit usaha mandiri koperasi siswa dan pembekalan jiwa enterpreneurship.'
  },
  {
    id: 'sekbid-4-2',
    name: 'Amanda Putri',
    role: 'Staf Koperasi Siswa Mandiri',
    division: 'Sekbid IV',
    divisionName: 'Kepribadian Unggul & Wawasan Kewirausahaan',
    classGrade: 'XII IPS 1',
    nis: '2223.10.120',
    email: 'amanda.putri@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
    bio: 'Manajemen inventaris perlengkapan sekolah dan merchandise resmi Adhirajasa.'
  },
  {
    id: 'sekbid-4-3',
    name: 'Bryan Jonathan',
    role: 'Staf Bazar & Usaha Kreatif',
    division: 'Sekbid IV',
    divisionName: 'Kepribadian Unggul & Wawasan Kewirausahaan',
    classGrade: 'X-5',
    nis: '2425.10.124',
    email: 'bryan.jonathan@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    bio: 'Fasilitator stan UMKM siswa pada festival seni dan pameran tahunan.'
  },
  {
    id: 'sekbid-4-4',
    name: 'Clarissa Devi',
    role: 'Staf Literasi Finansial',
    division: 'Sekbid IV',
    divisionName: 'Kepribadian Unggul & Wawasan Kewirausahaan',
    classGrade: 'XI MIPA 2',
    nis: '2324.11.129',
    email: 'clarissa.devi@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    bio: 'Pemberian edukasi pengelolaan uang saku digital dan pembukuan bisnis rintisan.'
  },

  // =================== SEKBID V: DEMOKRASI, HAM & LINGKUNGAN HIDUP ===================
  {
    id: 'sekbid-5-1',
    name: 'Salma Aulia',
    role: 'Koordinator Sekbid V',
    division: 'Sekbid V',
    divisionName: 'Demokrasi, HAM & Lingkungan Hidup',
    classGrade: 'XI MIPA 5',
    nis: '2324.11.138',
    email: 'salma.aulia@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Advokasi kesetaraan hak belajar, pengelolaan program Adiwiyata, dan pelestarian alam.'
  },
  {
    id: 'sekbid-5-2',
    name: 'Fikri Haikal',
    role: 'Staf Advokasi Hak Siswa',
    division: 'Sekbid V',
    divisionName: 'Demokrasi, HAM & Lingkungan Hidup',
    classGrade: 'XII MIPA 1',
    nis: '2223.10.142',
    email: 'fikri.haikal@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    bio: 'Pendampingan konsultasi hak asasi siswa dan penyusunan instrumen jajak pendapat.'
  },
  {
    id: 'sekbid-5-3',
    name: 'Nadia Eka Putri',
    role: 'Staf Green School & Bank Sampah',
    division: 'Sekbid V',
    divisionName: 'Demokrasi, HAM & Lingkungan Hidup',
    classGrade: 'X-3',
    nis: '2425.10.148',
    email: 'nadia.putri@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    bio: 'Pengelolaan pemilahan sampah organik & anorganik serta penanaman bibit pohon angkatan.'
  },
  {
    id: 'sekbid-5-4',
    name: 'Rendy Syahputra',
    role: 'Staf Edukasi Lingkungan Hidup',
    division: 'Sekbid V',
    divisionName: 'Demokrasi, HAM & Lingkungan Hidup',
    classGrade: 'XI IPS 1',
    nis: '2324.11.153',
    email: 'rendy.syahputra@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    bio: 'Kampanye pengurangan sampah plastik dan audit berkala kebersihan kantin sekolah.'
  },

  // =================== SEKBID VI: KREATIVITAS, KETERAMPILAN & SENI KRIYA ===================
  {
    id: 'sekbid-6-1',
    name: 'Farrel Danu',
    role: 'Koordinator Sekbid VI',
    division: 'Sekbid VI',
    divisionName: 'Kreativitas, Keterampilan & Kewirausahaan',
    classGrade: 'XII MIPA 3',
    nis: '2223.10.161',
    email: 'farrel.danu@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Pemberdayaan keterampilan aplikatif, riset prototipe, dan pameran kriya pelajar.'
  },
  {
    id: 'sekbid-6-2',
    name: 'Tasya Kamila',
    role: 'Staf Riset Inovasi & Prototipe',
    division: 'Sekbid VI',
    divisionName: 'Kreativitas, Keterampilan & Kewirausahaan',
    classGrade: 'XI MIPA 4',
    nis: '2324.11.166',
    email: 'tasya.kamila@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    bio: 'Pendampingan siswa dalam perancangan karya guna ulang dan inovasi teknologi tepat guna.'
  },
  {
    id: 'sekbid-6-3',
    name: 'Kevin Wijaya',
    role: 'Staf Kriya & Desain Produk',
    division: 'Sekbid VI',
    divisionName: 'Kreativitas, Keterampilan & Kewirausahaan',
    classGrade: 'X-6',
    nis: '2425.10.170',
    email: 'kevin.wijaya@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    bio: 'Desain instalasi artistik gerbang penyambutan dan dekorasi ramah lingkungan.'
  },
  {
    id: 'sekbid-6-4',
    name: 'Dea Amanda',
    role: 'Staf Workshop Keterampilan',
    division: 'Sekbid VI',
    divisionName: 'Kreativitas, Keterampilan & Kewirausahaan',
    classGrade: 'XI IPS 3',
    nis: '2324.11.175',
    email: 'dea.amanda@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    bio: 'Penyelenggaraan kelas keterampilan melukis totebag dan pembuatan sabun organik.'
  },

  // =================== SEKBID VII: KEBUGARAN JASMANI & REKREASI ===================
  {
    id: 'sekbid-7-1',
    name: 'Gilang Prakoso',
    role: 'Koordinator Sekbid VII',
    division: 'Sekbid VII',
    divisionName: 'Kebugaran Jasmani & Rekreasi',
    classGrade: 'XII IPS 1',
    nis: '2223.10.180',
    email: 'gilang.prakoso@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Pengorganisasian turnamen olahraga antarkelas (Class Meeting) dan liga futsal/basket.'
  },
  {
    id: 'sekbid-7-2',
    name: 'Aditya Pratama',
    role: 'Staf Olahraga Prestasi',
    division: 'Sekbid VII',
    divisionName: 'Kebugaran Jasmani & Rekreasi',
    classGrade: 'XI MIPA 1',
    nis: '2324.11.184',
    email: 'aditya.pratama@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    bio: 'Penanggung jawab pembinaan atlet siswa untuk O2SN dan pertandingan persahabatan.'
  },
  {
    id: 'sekbid-7-3',
    name: 'Zaky Alamsyah',
    role: 'Staf Pertandingan Antarkelas',
    division: 'Sekbid VII',
    divisionName: 'Kebugaran Jasmani & Rekreasi',
    classGrade: 'X-2',
    nis: '2425.10.189',
    email: 'zaky.alamsyah@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    bio: 'Perangkat pertandingan, perwasitan catur cepat, dan turnamen bulutangkis sekolah.'
  },
  {
    id: 'sekbid-7-4',
    name: 'Maya Kartika',
    role: 'Staf Kebugaran & Senam Bersama',
    division: 'Sekbid VII',
    divisionName: 'Kebugaran Jasmani & Rekreasi',
    classGrade: 'XI IPS 2',
    nis: '2324.11.193',
    email: 'maya.kartika@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    bio: 'Instruktur senam kesegaran jasmani berkala pada program Sehat Bersama Civitas.'
  },

  // =================== SEKBID VIII: APRESIASI SASTRA & SENI BUDAYA ===================
  {
    id: 'sekbid-8-1',
    name: 'Clara Salsabila',
    role: 'Koordinator Sekbid VIII',
    division: 'Sekbid VIII',
    divisionName: 'Apresiasi Sastra & Seni Budaya',
    classGrade: 'XI Bahasa',
    nis: '2324.11.201',
    email: 'clara.salsabila@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Direktur artistik Pentas Seni Gita Swara Adhirajasa dan pembinaan sanggar seni tradisi.'
  },
  {
    id: 'sekbid-8-2',
    name: 'Bunga Citra',
    role: 'Staf Musik Ansambel & Karawitan',
    division: 'Sekbid VIII',
    divisionName: 'Apresiasi Sastra & Seni Budaya',
    classGrade: 'XII Bahasa',
    nis: '2223.10.205',
    email: 'bunga.citra@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    bio: 'Pengarah kolaborasi gamelan karawitan nusantara dengan ansambel akustik modern.'
  },
  {
    id: 'sekbid-8-3',
    name: 'Alden Michael',
    role: 'Staf Teater & Sastra Teatrikal',
    division: 'Sekbid VIII',
    divisionName: 'Apresiasi Sastra & Seni Budaya',
    classGrade: 'X-4',
    nis: '2425.10.210',
    email: 'alden.michael@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    bio: 'Kurasi pementasan monolog Bulan Bahasa dan festival baca puisi patriotisme.'
  },
  {
    id: 'sekbid-8-4',
    name: 'Hana Salsabila',
    role: 'Staf Seni Visual & Pameran',
    division: 'Sekbid VIII',
    divisionName: 'Apresiasi Sastra & Seni Budaya',
    classGrade: 'XI MIPA 3',
    nis: '2324.11.214',
    email: 'hana.salsabila@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
    bio: 'Tata letak lorong pameran lukisan dan fotografi karya siswa di selasar sekolah.'
  },

  // =================== SEKBID IX: TEKNOLOGI INFORMASI & KOMUNIKASI (TIK) ===================
  {
    id: 'sekbid-9-1',
    name: 'Rian Daniswara',
    role: 'Koordinator Sekbid IX',
    division: 'Sekbid IX',
    divisionName: 'Teknologi Informasi & Komunikasi',
    classGrade: 'XII MIPA 5',
    nis: '2223.10.220',
    email: 'rian.daniswara@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Kepala arsitektur portal digital OSIS, tata kelola cloud server, dan literasi keamanan siber.'
  },
  {
    id: 'sekbid-9-2',
    name: 'Alifia Rahma',
    role: 'Staf Redaksi Website & Media Sosial',
    division: 'Sekbid IX',
    divisionName: 'Teknologi Informasi & Komunikasi',
    classGrade: 'XI MIPA 3',
    nis: '2324.11.225',
    email: 'alifia.rahma@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
    bio: 'Editor warta digital sekolah, penulisan rilis pers program kerja, dan feeds Instagram.'
  },
  {
    id: 'sekbid-9-3',
    name: 'Gabriel Natanael',
    role: 'Staf Multimedia & Livestreaming',
    division: 'Sekbid IX',
    divisionName: 'Teknologi Informasi & Komunikasi',
    classGrade: 'X-1',
    nis: '2425.10.230',
    email: 'gabriel.natanael@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    bio: 'Operator switch multi-kamera penyiaran langsung di kanal resmi YouTube sekolah.'
  },
  {
    id: 'sekbid-9-4',
    name: 'Vina Aprilia',
    role: 'Staf Desain Grafis & AI Media',
    division: 'Sekbid IX',
    divisionName: 'Teknologi Informasi & Komunikasi',
    classGrade: 'XI IPS 1',
    nis: '2324.11.235',
    email: 'vina.aprilia@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
    bio: 'Pembuatan infografis panduan siswa, poster publikasi agenda, dan identitas visual kabinet.'
  },

  // =================== SEKBID X: KOMUNIKASI BAHASA INTERNASIONAL ===================
  {
    id: 'sekbid-10-1',
    name: 'Jessica Maheswari',
    role: 'Koordinator Sekbid X',
    division: 'Sekbid X',
    divisionName: 'Komunikasi Bahasa Internasional',
    classGrade: 'XI MIPA 1',
    nis: '2324.11.240',
    email: 'jessica.maheswari@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    isCoordinator: true,
    bio: 'Penggagas Adhirajasa Model United Nations (MUN) dan ketua delegasi debat bahasa Inggris.'
  },
  {
    id: 'sekbid-10-2',
    name: 'Jonathan Darren',
    role: 'Staf Diplomasi & MUN Club',
    division: 'Sekbid X',
    divisionName: 'Komunikasi Bahasa Internasional',
    classGrade: 'XII MIPA 2',
    nis: '2223.10.245',
    email: 'jonathan.darren@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    bio: 'Mentor riset resolusi sidang PBB simulasi dan teknik public speaking diplomasi pemuda.'
  },
  {
    id: 'sekbid-10-3',
    name: 'Sabrina Alya',
    role: 'Staf English Debate League',
    division: 'Sekbid X',
    divisionName: 'Komunikasi Bahasa Internasional',
    classGrade: 'X-3',
    nis: '2425.10.250',
    email: 'sabrina.alya@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    bio: 'Penyelenggara kompetisi debat parliamentary bahasa Inggris antar kelas dan sekolah mitra.'
  },
  {
    id: 'sekbid-10-4',
    name: 'Arkan Rafif',
    role: 'Staf Language Exchange Clinic',
    division: 'Sekbid X',
    divisionName: 'Komunikasi Bahasa Internasional',
    classGrade: 'XI MIPA 4',
    nis: '2324.11.254',
    email: 'arkan.rafif@osis.sman1adhirajasa.sch.id',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    bio: 'Klinik pendampingan persiapan tes TOEFL/IELTS dasar bagi siswa pelamar beasiswa kuliah.'
  }
];
